<a href="https://colab.research.google.com/github/TPincher/ECommerceSite/blob/main/tensorMaths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [25]:
tensorA = torch.tensor([1,2,3,4])
tensorB = torch.tensor([5,6,7,8])

In [4]:
# Addition shorthand
tensorA + tensorB

tensor([ 6,  8, 10, 12])

In [5]:
# Addition longhand
torch.add(tensorA, tensorB)

tensor([ 6,  8, 10, 12])

In [6]:
# Subtraction
tensorB - tensorA

tensor([4, 4, 4, 4])

In [7]:
torch.sub(tensorB, tensorA)

tensor([4, 4, 4, 4])

In [8]:
# Multiplication
tensorA * tensorB

tensor([ 5, 12, 21, 32])

In [9]:
torch.mul(tensorA, tensorB)

tensor([ 5, 12, 21, 32])

In [10]:
# Division - note that this converts to a float
tensorB / tensorA

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
torch.div(tensorB, tensorA)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Remainder modulus
tensorB % tensorA

tensor([0, 0, 1, 0])

In [13]:
torch.remainder(tensorB, tensorA)

tensor([0, 0, 1, 0])

In [14]:
# Exponents
torch.pow(tensorA, tensorB)

tensor([    1,    64,  2187, 65536])

In [15]:
# You can also perform these operations on the first tensor operand
tensorA.add(tensorB)

tensor([ 6,  8, 10, 12])

In [26]:
# Reassignment. Anything that uses an underscore like the below in an IN-PLACE operation
tensorA.add_(tensorB)

tensor([ 6,  8, 10, 12])

In [27]:
tensorA

tensor([ 6,  8, 10, 12])